### ISSUE TITLE
Improve the Book(resolver, model) example 

### ISSUE THREAD

**Issue by malvfr** [malvfr/serverless-graphql-nestjs#1]
It would be nice to have more fields in the Book example. You can add an Author relationship as well.

**Comment by Croustys** [comment]
I'd like to try working on that one!

**Comment by malvfr** [comment]
Ok @Croustys, thanks. Please assign the issue to yourself.

**Comment by hvsio** [comment]
Is it still free to take? :)

**Comment by malvfr** [comment]
@hvsio Well, since the previous user did not assign the issue to himself/herself, I think you can take it

**Comment by hvsio** [comment]
I believe you need to assign me to it as I do not have the possibility to do it
